dist: trusty
sudo: false

language: scala

jdk: oraclejdk8

scala:
   - 2.12.4

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  # per http://www.scala-sbt.org/1.0/docs/Travis-CI-with-sbt.html
  # this cleanup of the cached directories suppresses unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
